Update build script

diff --git a/pkgbuild/void/install b/pkgbuild/void/install
--- a/pkgbuild/void/install
+++ b/pkgbuild/void/install
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ ! -z $xi ]]; then
+    echo "command xi not found. Is xtools installed?"
+    exit 1
+fi
+
 # TODO: make versioning 'correct' when this package
 # no longer needs to build the latest commit
 TAG=$(git describe --tags --abbrev=0 | sed 's/^v//')
@@ -8,15 +13,19 @@ REV_COUNT=$(git rev-list --count HEAD)
 VERSION="${TAG}+r${REV_COUNT}.${HASH}"
 
 if [[ ! -d "void-packages" ]]; then
-    echo "Looks like void-packages git repository does not exist. Cloning..."
-    git clone --depth=1 git@github.com:void-linux/void-packages.git
+    git clone --depth=1 git@github.com:void-linux/void-packages.git void-packages
     cd void-packages || exit 1
     ./xbps-src binary-bootstrap
-    mkdir -p srcpkgs/cldl
 else
     cd void-packages || exit 1
 fi
 
+echo "Copying template file..."
+if [[ ! -d ./srcpkgs/cldl ]]; then
+    mkdir -p srcpkgs/cldl
+fi
 sed "s/version=.*/version=$VERSION/" ../template >./srcpkgs/cldl/template
+
+echo "Packaging..."
 ./xbps-src pkg cldl
 sudo xi -f cldl
